target("loader")
    set_kind("binary")
    set_strip("all")
    set_optimize("fastest")
    set_targetdir("bin")
    add_syslinks("dl")
    add_files("src/loader.cpp")
    add_files("src/utils/utils.cpp")
    add_includedirs("include", {public=true})
    add_includedirs("src/utils", {public=true})

target("mod_cache")
    set_default(false)
    set_kind("shared")
    set_targetdir("mods")
    add_files("test/mod_cache.cpp")
    add_deps("loader")

target("mod_parse")
    set_default(false)
    set_kind("shared")
    set_targetdir("mods")
    add_files("test/mod_parse.cpp")
    add_deps("loader")

target("mod_recv")
    set_default(false)
    set_kind("shared")
    set_targetdir("mods")
    add_files("test/mod_recv.cpp")
    add_deps("loader")