target("loader")
    set_kind("binary")
    set_strip("all")
    set_optimize("fastest")
    set_targetdir("bin")
    add_syslinks("dl")
    add_files("src/loader.cpp")
    add_files("src/utils/utils.cpp")
    add_includedirs("include", {public=true})
    add_includedirs("src/utils", {public=true})
